# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeerTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeerTracker
  pod 'couchbase-lite-ios', '~> 1.3.1'
  

  target 'BeerTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
